kafka:
  topic: sample-etl
  bootstrap-servers: "localhost:9092"
  producer-type: async
  acks: all
  retries: 2
  batch-size: 16384
  key-serializer: org.apache.kafka.common.serialization.StringSerializer
  value-serializer: org.apache.kafka.common.serialization.StringSerializer

cache:
  location: cache-data